### ISSUE TITLE
Rename MU Density to `MetersetMap`

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1051]
Hi @sjswerdloff,

You came up with a more descriptive name for MU Density. I can't remember what it was though, I remember I liked it though...

**Comment by sjswerdloff** [comment]
I think I suggested "MU map"

**Comment by SimonBiggs** [comment]
Or maybe I should just call it "fluence_map" as that is what it is referred to in the literature:

https://www.nature.com/articles/s41598-019-52262-x

It's clear that it is a map of the fluence, not a true fluence. So maybe that distinction is sufficient.

**Comment by sjswerdloff** [comment]
From the paper you referenced
>The pixel values of the fluence maps and the differences are presented in fractional monitor units (fMU).
so... yes.
But...
As a Medical Physicist, I expect a fluence map to have units of number of particles (e.g. photons) per unit area, e.g. 1/cm^2
But fluence with that definition is proportional to Monitor Units (meterset).  So it's within a scaling constant, with the constant having dimensions.

In RT Ion Plan, the units of meterset are either MU or NP (Number of Particles), both of which are dimensionless.

In Photons (RT Plan), if you have 100 MU, it implies a certain #photons per unit area, and has nominally been calibrated so that a 10cm x 10cm field will have a dose of 1 Gray at 10cm depth.  The # of photons per unit area won't change with an MLC in place(ignoring scatter) but the total number of photons will (because there is only a fraction of the area of the open field involved).

But for pencil beam scanning (spot scanning) in particle therapy, the same number of particles can get delivered to an arbitrary number of spots of nearly arbitrary size (at least in a given control point).  The scaling here would be the number of particles per spot divided by the "area" of the spot (as a function of it's x and y spot size parameters, treating the spot as an ellipse)

I tend to use the phrase meterset rather than MU, so another possibility is MetersetMap.
But fluence map, if the units are provided, is reasonable.

**Comment by SimonBiggs** [comment]
Yup, completely fair. I think `MetersetMap` is the go. I am liking this alignment with DICOM terminology (meterset vs MU). I think if there is ever an object or representation or name in the DICOM standard that makes sense and is both recognisable to the user and not easily confused with something else, I suspect it should be a default approach to naming in a consistent fashion.
