### ISSUE TITLE
support for Raspberry Pi 4

### ISSUE THREAD

**Issue by sjswerdloff** [pymedphys/pymedphys#1079]
pymedphys takes a bit of work to get installed on Raspberry Pi 4 (Raspbian OS)
When installing
pip install pymedphys[user,tests]

[install_jpeg.sh.txt](https://github.com/pymedphys/pymedphys/files/5339440/install_jpeg.sh.txt)
[apt_get_for_pymedphys_on_rpi.sh.txt](https://github.com/pymedphys/pymedphys/files/5339441/apt_get_for_pymedphys_on_rpi.sh.txt)
i had to do a number of apt-get install
manually install jpeg
and then
pip install pyyaml pytest pytest-pylint

some of the apt-get stuff might be overkill because I was also trying to get 
poetry install -E dev 
to work (ultimately I got stuck on pyarrow, I managed to install scipy from a wheel)

**Comment by sjswerdloff** [comment]
test_structure_dedupe.py failed.
But all of the other tests passed.

**Comment by SimonBiggs** [comment]
By the way, there's an ARM docker image. Did a bit of a search through a few other GitHub repos, and this is how they use GitHub Actions to run an ARM image:

https://github.com/kivy/kivy/blob/da621743f32960e2a4f2f4c3f1a1d6d550da4b8e/.github/workflows/rpi_wheels.yml#L21

So that could be used to make sure that PyMedPhys is having its CI also run on ARM.

**Comment by SimonBiggs** [comment]
Also... this looks interesting, software to manage rolling out updates to a fleet of Rasberry Pi's:
https://www.balena.io/what-is-balena

**Comment by sjswerdloff** [comment]
pyarrow solution at
https://discuss.streamlit.io/t/raspberry-pi-streamlit/2900/30
