### ISSUE TITLE
Lingering alerts from PR #1107

### ISSUE THREAD

**Issue by sjswerdloff** [pymedphys/pymedphys#1109]
This pull request **introduces 4 alerts** and **fixes 1** when merging 28cad83887de752d393327a88954ee4f1c078093 into 87a96ff0a7c03892c9f260f3fd50a3b486099c46 - [view on LGTM.com](https://lgtm.com/projects/g/pymedphys/pymedphys/rev/pr-705c73840b02a21e06c0f552c9c795e4ddb4f147)

**new alerts:**

* 2 for Unused import
* 2 for Module is imported with &#39;import&#39; and &#39;import from&#39;

**fixed alerts:**

* 1 for Unused import

_Originally posted by @lgtm-com in https://github.com/pymedphys/pymedphys/pull/1107#issuecomment-718721882_

**Comment by SimonBiggs** [comment]
Any unused imports within _imports.py can be ignored. Also, LGTM errors within site-specific files or prototyping code can be ignored.

They got flagged here because I ran:

```
poetry run pre-commit run --all-files
```

Which applied black and isort formatting across the whole repo. Which essentially re-flagged errors that were already existing.
