### ISSUE TITLE
A moment for bikeshedding

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1159]
Before making the GUI URL live it would be worth narrowing down once and for all the name for "mudensity". One of the key issues with the name is that it invokes a 3D connotation with the word "density". In this stage of development this is something that can be changed, but the window is rapidly closing.

Given people are used to the term "fluence map" I think the change to map proposed by @sjswerdloff fits much better. My thought is to stick with mu, however. I can however certainly be swayed to go with "metersetmap" as originally proposed. I can't think of another "map" where the "units" instead of the "thing" is used in the naming, which is certainly in favour of meterset.

So the change would be "mudensity" --> "mumap". The previous name will be kept around for a long while, but it'll be marked as deprecated. Docs, text, function references, and URLs will be changed appropriately.

If we are decided and are to go forward with the change, the goal would be to make this change before "publishing" the PyMedPhys GUI URL.

**Comment by Matthew-Jennings** [comment]
FWIW, I believe "mumap" is best. In my mind at least, "meterset" specifically refers to the total MU count that has been programmed for a beam (the "meter" that is "set"). To me, MU are the meterset's units, and it is these units that are being individually counted and displayed in the map.

I think the DICOM standard kinda agrees, since the keyword _BeamMeterset_ has the following definition:

Machine setting to be delivered for current Beam, specified in Monitor Units (MU) or minutes as defined by Primary Dosimeter Unit (300A,00B3) (in RT Beams Module) for referenced Beam.

**Comment by sjswerdloff** [comment]
I would refer you to Section C.8.8.21.2
for convenience
https://dicom.innolitics.com/ciods/rt-beams-treatment-record/rt-beams-session-record/30080020/30080040/30080042

but as long as whatever name is chosen is used consistently, it's not really a problem

**Comment by Matthew-Jennings** [comment]
Fair point!

**Comment by Matthew-Jennings** [comment]
Maybe meterset is best then... if it was dose, we'd call it dose_map, not gy_map...

**Comment by sjswerdloff** [comment]
I think most clinicians will resonate with MU rather than meterset.
For conventional therapy, as long as it isn't Cobalt, that's the way meterset is discussed.
I apologize if I was being pedantic, but alot of my job involves educating people about DICOM.
If this doesn't get used for Cobalt or Carbon Ion therapy, "MU map" will work well.

**Comment by SimonBiggs** [comment]
Although MU strictly speaking is the units by both what it stands for (monitor units) and within the DICOM standard. Nevertheless, colloquially within the clinic I find that "MU" or "monitor units" is used interchangeably as the name of the unit but also the name of the parameter itself. In the case of dose_map vs gy_map we would never say "Don't let the Gy be more than 10 over there". But in the case of MU I would happily say "Set the MU to 100 for this beam". Also, in conversation, within our clinic, people would look at me a little weird if I said, "set the meterset to 100 MU for this beam". The word "meterset" just isn't used that often within the clinic, at least in my experience.

So, given it is much of a muchness (it is bikeshedding nonetheless), `metersetmap` is the choice to align more closely with the DICOM standard, `mumap` is the choice to align with common colloquial usage of names within the clinic. If the thing being described was directly described within the DICOM standard (a beam eye view MU display) then we should always defer to use its naming convention. In this case though, I think deferring to colloquialism may be more discernible by our users.

**Comment by SimonBiggs** [comment]
mudensity

**Comment by SimonBiggs** [comment]
metersetmap

**Comment by SimonBiggs** [comment]
mumap

**Comment by SimonBiggs** [comment]
So, I slept on it, and I realised this morning that it's going to erk me to no end if it's not strictly correct. We are physicists... We're in the business of being strictly correct.

So on that note, if there's no objection, I'll make the change to metersetmap tonight. :)
