### ISSUE TITLE
Thoughts on anonymisation/pseudonymisation

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#1170]
Hi @SimonBiggs and @sjswerdloff,

I'm sorry I wasn't able to spare much time when @sjswerdloff was making lovely changes to anonymise. I'm hoping to belatedly get up to speed, both on the backend and progress with the app. 

A relatively pertinent issue we have at our department at the moment is the constant need our therapists and admin staff have for us to anonymise DICOM files for clinical trials. I'd love to have an app ready made for them to safely use, and figure it'd be best in PyMedPhys, especially considering the progress @sjswerdloff has aleady made.

So I guess I have a few questions:

1. What is the status of GUI development? Can I help?
2. I've noticed that the `is_anonymised_xxx()` functions are in `core`. Should they be in `api`? I did intend for them to be exposed..
3. How has the default replacement strategy changed? What are your thoughts on its current status? Can it be improved? E.g. I've only very recently noticed DICOM's De-identification Method Attribute, which I don't think we set at the moment (or at least, never used to). Can we aim to claim conformance to a DICOM Application Level Confidentiality Profile?

**Comment by sjswerdloff** [comment]
Hi @Matthew-Jennings 

  While the GUI is very simplistic and is limited to pseudonymisation, it is functional.
There is plenty of room for making it more sophisticated, and help is always appreciated.
I imagine it would be nice to have identifying-key exclusion available through the GUI.  Whatever is needed by real world users should drive the issues/feature request list.

  Note that I created another very simple GUI based on PyQT: https://github.com/sjswerdloff/qtpseudo.git
and I made an effort to provide a setup.py and setup_macos.py for people to generate a standalone binary for ease of deployment.  Using Simon's current naming convention, I would call it Raw, or Experimental if one wanted to be generous...

  I don't know if I would expose is_anonymised_xxx().  Whether something is anonymised is a judgement call.
I think that warrants a completely separate discussion.

  I don't think we changed the default replacement strategy for anonymise, although we did address identifiers in nested sequences.  Note that UIDs are addressed in pseudonymise, but not anonymise.

  I had not seen the De-identification Method attribute until a day or so ago.
That counts as a very useful small enhancement.  

I don't think we can claim conformance to a DICOM Application Level Confidentiality Profile, but I would need to double check.  I scanned through some discussion by David Clunie, and I think there are a handful of elements that we don't eliminate (and I think we don't eliminate them because the data becomes clinically not useful without it) that are expected to be eliminated for the more useful level(s).  I'm not quite at the point where I'm ready to go toe-to-toe with WG-6.  Or to generate a Change Proposal.
But we probably could put together a statement that indicates where we are with respect to a particular level of Confidentiality and call out those elements that cause us to "not conform" and explain why we aren't eliminating those.
I would prefer to have configuration (in config.toml) of salt for the hash for pseudonymisation to make it more resistant to rainbow table attacks, and I want to provide a more appropriate (and variable) value for earliest study date in a set of data to get date jittering that can't be reversed based on knowing the code. 

I had mentioned to @SimonBiggs that there is a systems level approach involving an SCP (Storage Class Provider), an SCU, and processing in between to make for a more workflow friendly solution.  @pchlap is nearly done with a PR for a nice SCP.
That way people don't have to have files and do file selection.  They can just export to the SCP, or do a Q/R to the SCP, and then pseudonymised data will get automatically transmitted to the (configured/designated) destination.

We also don't have generation of a re-identification list (to be kept by those who have the original data already).

>for us to anonymise DICOM files for clinical trials

We aren't populating the Clinical Trials modules.
That's a whole separate area of discussion.  Is that needed for your current circumstances (and not addressed using another tool)?

**Comment by Matthew-Jennings** [comment]
Thanks for the comprehensive reply, @sjswerdloff!

> I imagine it would be nice to have identifying-key exclusion available through the GUI.
Agreed, that sounds like a lovely feature.

> Whatever is needed by real world users should drive the issues/feature request 
Agreed.

> Note that I created another very simple GUI based on PyQT
Great! I'll take a look :)

> I don't know if I would expose is_anonymised_xxx(). Whether something is anonymised is a judgement call.
Good point. Although I think that if we can claim comformance to one of the less strict Confidentiality Profiles, we can expose a function that tests comformance to it. But we're not there (yet).

> I don't think we can claim conformance to a DICOM Application Level Confidentiality Profile, but I would need to double check.
If I recall correctly, when I was looking at all of this, I remember coming to the conclusion that we'd be pretty close! But I may have been mistaken. I'll look myself when I get the time.

> I would prefer to have configuration (in config.toml) of salt for the hash for pseudonymisation to make it more resistant to rainbow table attacks, and I want to provide a more appropriate (and variable) value for earliest study date in a set of data to get date jittering that can't be reversed based on knowing the code.
I have limited expertise here and would love to learn.

> But we probably could put together a statement that indicates where we are with respect to a particular level of Confidentiality and call out those elements that cause us to "not conform" and explain why we aren't eliminating those.
I think this is a very a good idea

> I think there are a handful of elements that we don't eliminate (and I think we don't eliminate them because the data becomes clinically not useful without it)
Yeah, one example might be PixelData. But I am under the impression that one of the lower level Confidentiality Profiles don't require this. There are also examples where PixelData has a vanishingly low likelihood of containing identifying information (e.g. in the RTDOSE modality).

> I had mentioned to @SimonBiggs that there is a systems level approach involving an SCP (Storage Class Provider), an SCU, and processing in between to make for a more workflow friendly solution. @pchlap is nearly done with a PR for a nice SCP.
That way people don't have to have files and do file selection. They can just export to the SCP, or do a Q/R to the SCP, and then pseudonymised data will get automatically transmitted to the (configured/designated) destination.
That does sound lovely!

> We aren't populating the Clinical Trials modules. That's a whole separate area of discussion. Is that needed for your current circumstances (and not addressed using another tool)?
Sorry, I wasn't referring to, say, the Clinical Trials Study DICOM Module, I just was noting a real world application we have for anonymising CT, RTSTRUCT, RTPLAN and RTDOSE files

**Comment by Matthew-Jennings** [comment]
> While the GUI is very simplistic and is limited to pseudonymisation, it is functional.

What would you and @SimonBiggs like to see happen before it's taken out of "Raw" and considered "Mature" or "Maturing"?

One obvious thought is documentation...

**Comment by SimonBiggs** [comment]
> > While the GUI is very simplistic and is limited to pseudonymisation, it is functional.
> 
> What would you and @SimonBiggs like to see happen before it's taken out of "Raw" and considered "Mature" or "Maturing"?
> 
> One obvious thought is documentation...

Have psudononymise be moved out of the experimental part of PyMedPhys, have greater coverage of the end to end testing of the GUI, and have it be in use regularly at at least one of our sites ideally (being dogfooded)

**Comment by SimonBiggs** [comment]
> I would prefer to have configuration (in config.toml) of salt for the hash for pseudonymisation to make it more resistant to rainbow table attacks

This can be set up so that if the salt isn't inside the config.toml it gets randomly created on first run...
