### ISSUE TITLE
A WLutz Arc paper

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1426]
Hi @sjswerdloff,

There's going to be a significant amount of review around this WLutz Arc coming through in the near future as this project is moved into stable. Do you think one of the outcomes of the project should potentially be a journal article?

Would you (and others who end up having a deep contribution) be interested in writing a Journal Article (or maybe technical note?... whatever is more appropriate) on this with me?

**Comment by sjswerdloff** [comment]
I think it's worth either an article or technical note.  I'm not sure which.
I'll ask a friend of mine who is more involved in the "publish or perish" side of things which he thinks is more appropriate.

But I don't feel like I've made that deep of a contribution to it (yeah, I did a fair amount of code review, but I didn't contribute design or algorithms).  If you want to say "thanks" to people in your article, I would be happy to be on that list.

If there is significant additional work and I'm involved in that (design, algorithms, etc.), then I'll re-consider your (kind) offer to have me as a co-author.

**Comment by SimonBiggs** [comment]
Kk, I'm not really used to how this "who gets to be an author" thing works. To be honest I don't think I could really much be bothered writing a paper where I'm the only author...

**Comment by sjswerdloff** [comment]
If you want help writing the paper, I'm happy to help.  And if my work in writing the paper is significant, then it is appropriate for me to be listed as an author.  Simply editing a paper doesn't count as significant (although that is real work!) 

The rules have changed over time for authorship.  I was never a fan of people high up the ladder being listed as an author just because... 

I look at it in terms of the equivalent to intellectual property.  Did someone think of something that made a difference? 
Just running a gel doesn't make you a contributor.  Tweaking the content of the gel, which then allowed for better discrimination that let someone identify a protein which got tagged through some brilliant new technique... That counts for me. 

So if I made a review suggestion that took the code from 'not practical in the clinic' but still theoretically interesting, and made it practical in the clinic, to me that would count. 

It's worth publishing if people aren't doing the test because 
A) no one had thought of it 
B) they would have to do it manually and its not clinically practical 

And then you produced the automation tool (and perhaps the basic idea as well)

If I understand correctly the technique under discussion is (B).  Well worth a technical note if not a method paper.

**Comment by SimonBiggs** [comment]
> A) no one had thought of it

I haven't found any references anywhere else to the idea...

> If you want help writing the paper, I'm happy to help. And if my work in writing the paper is significant, then it is appropriate for me to be listed as an author.

If you were interested, I would be interested in that... it may be the difference between me not bothering writing it... to actually having the paper exist...
