### ISSUE TITLE
Mosaiq automated testing review

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1489]
Heya @pchlap,

Might you be interested in undergoing the review of the following PRs:

* https://github.com/pymedphys/pymedphys/pull/1486
* https://github.com/pymedphys/pymedphys/pull/1487
* https://github.com/pymedphys/pymedphys/pull/1488

They create test coverage of the Mosaiq SQL query helper functions within PyMedPhys. I'm not sure if you've found that part of PyMedPhys helpful, but if you do happen to use it, it'd be awesome to get your review on those tests 🙂.

Cheers,
Simon

**Comment by pchlap** [comment]
Hi @SimonBiggs 

looks like some really great work on this, but I might have to pass unfortunately since I am a little swamped at the moment before I take a week of annual leave next week.

Hoping that once I am back I will have a bit more time to jump back into a few outstanding pymedphys things :)

Cheers
Phil

**Comment by SimonBiggs** [comment]
All good :)

Thanks Phil :)
