### ISSUE TITLE
DICOM networking failing with pynetdicom >= 2.0

### ISSUE THREAD

**Issue by scaramallion** [pymedphys/pymedphys#1606]
Some of the SOP Class object names have changed in v2.0 (like `sop_class.VerificationSOPClass` -> `sop_class.Verification`), you might want to pin v1.5.7 or update to v2.0.

**Comment by SimonBiggs** [comment]
Cheers for the heads up. Thanks @scaramallion.

@pchlap or @sjswerdloff did either of you want to see if you can look into this?

**Comment by sjswerdloff** [comment]
> Cheers for the heads up. Thanks @scaramallion.
> 
> @pchlap or @sjswerdloff did either of you want to see if you can look into this?

I will take a look shortly (but it might be this weekend)

**Comment by SimonBiggs** [comment]
Thanks @sjswerdloff :slightly_smiling_face:

**Comment by sjswerdloff** [comment]
I'm making progress (burned a few hours until discovering an extra copy of pymedphys in my site-packages that was getting picked up and used instead of my code changes).
We have two places where VerificationSOPClass is being used.
My intent is to start with the same replacement approach in each (employing hasattr(...) ) and we can refactor from there.

**Comment by SimonBiggs** [comment]
Yup, sounds like a reasonable approach to me.

**Comment by scaramallion** [comment]
Thanks!
