### ISSUE TITLE
error message in gamma analysis for a feet-in DICOM

### ISSUE THREAD

**Issue by guanfada** [pymedphys/pymedphys#1660]
@SimonBiggs 
For most of cases I tested using gamma analysis, the patient's CT was head-in.
But for a special case with a tumor in the leg, the patient's CT was feet-in, and then I got the below "ascending" error. 
Any ideas about this? 
Thanks

   exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/PyCharmVenv/gamma 3D TBB and TBC/001/gamma3DForDcm001.py", line 102, in <module>
    **gamma_options)
  File "E:\PyCharmVenv\venv\lib\site-packages\pymedphys\_gamma\implementation\shell.py", line 128, in gamma_shell
    quiet,
  File "E:\PyCharmVenv\venv\lib\site-packages\pymedphys\_gamma\implementation\shell.py", line 263, in from_user_inputs
    fill_value=np.inf,
  File "E:\PyCharmVenv\venv\lib\site-packages\scipy\interpolate\interpolate.py", line 2475, in __init__
    "ascending" % i)
ValueError: The points in dimension 0 must be strictly ascending

**Comment by SimonBiggs** [comment]
That is interesting. It's an error message from the trilinear interpolation being utilised. But the fix would be to make it so that should a given axis be descending then within the gamma function that axis and the corresponding axis within the dose grid would just need to be flipped prior to passing it to the interpolation function.

@guanfada, might you be able to make some dummy data and create a function that loads up that dummy set and then tries to run the gamma function. We can then include that within the test suite to show the bug:

https://github.com/pymedphys/pymedphys/blob/ff7e8c54af62c85468a967f7f5abee862b0a590b/lib/pymedphys/tests/gamma/test_gamma_shell.py#L116-L127

And from there, once we have a failing test, we can take the steps required to make a fix :slightly_smiling_face:.

@Matthew-Jennings, might you be interested in providing support here?

**Comment by Matthew-Jennings** [comment]
> @Matthew-Jennings, might you be interested in providing support here?

Sure!

---------------

@guanfada: Just to flesh out @SimonBiggs' request a little:

Our preferred process for a bugfix like this is to employ [Test-driven Development (TDD)](https://en.wikipedia.org/wiki/Test-driven_development). When we identify a bug, we:
   1. write a **_minimal_** test in our automated test suite that replicates the bug. 
   2. run the test suite and ensure that this new test fails
   3. write the necessary library code to fix the bug
   4. check that both our new test (bug is fixed) and all existing tests (bugfix didn't break other code) now pass.

Where possible, we try to empower new contributors like yourself to do this (they can vary substantially in experience with TDD!).

*Do you think that you're in a position to give it a go?*

There are several existing tests that can be used as templates to achieve this, and it locks your identity into the git history forever as the person who fixed the bug :)

P.S., please forgive me if you're familiar with all of this. We get budding contributors to PyMedPhys with a wide range of coding experience and err on the side of over-explaining.

**Comment by guanfada** [comment]
@SimonBiggs If I understand correctly, I can create two dummy DICOM RD files with the feet-in orientation, and then do a test, right? 
@Matthew-Jennings Thanks a lot for the detailed instructions! I don't have any experience in TDD :-) Let me try.

**Comment by SimonBiggs** [comment]
> If I understand correctly, I can create two dummy DICOM RD files with the feet-in orientation, and then do a test, right?

Yup, that's right. And the test is essentially just running those two files through the gamma function and having it replicate that error above.

**Comment by Matthew-Jennings** [comment]
> @Matthew-Jennings Thanks a lot for the detailed instructions! I don't have any experience in TDD :-) Let me try.

Great!

PyMedPhys is a complex beast and there's no need to spend significant time trying to grok it yourself. There might be questions you have that we could answer very quickly to save you time. Please don't hesitate to ask for help.

I would be perfectly happy to have a Zoom meeting or similar to get you started. @SimonBiggs too, I daresay ;p

**Comment by guanfada** [comment]
> I would be perfectly happy to have a Zoom meeting or similar to get you started. @SimonBiggs too, I daresay ;p

@Matthew-Jennings @SimonBiggs 
Fantastic. Let me first prepare two dummy DICOM files with feet-in, probably next week. I will let you guys know then.

**Comment by guanfada** [comment]
@Matthew-Jennings My two Dummy dicom files are ready, and I got the same error.
ValueError: The points in dimension 0 must be strictly ascending

**Comment by Matthew-Jennings** [comment]
Hi @guanfada,

Okay, so there are a few ways to approach this:

1. You could create and upload new, full DICOM files to the test data (stored on Zenodo) and write tests that run on this data. This is probably the least preferable option, since:
   - it requires more to set up and adds to the size of the existing PyMedPhys test data stored in Zenodo, which we'd like to keep small, and
   - it makes the test suite slower (additional files would need to be downloaded and read on every test run)
   
2. You could create suitable temporary DICOM datasets in python using `pydicom` and write new tests that tests on those datasets.

3. You could add to an existing test by temporarily altering an existing test dataset (made using option 2) and running tests on those datasets

--------------------------------------

For reference:

- [test_dicom_dose_constancy()](https://github.com/pymedphys/pymedphys/blob/398d741427843097e73092acc22de0460d238c4d/lib/pymedphys/tests/dicom/test_dose.py#L37-L63) employs option 1. Notice that the test is downloading a DICOM file called `RD.wedge.dcm` and a baseline JSON file stored in a zip file called `lfs-wedge_dose_baseline.zip` and compares the two against each other as a constancy check

- [test_sum_doses_in_datasets()](https://github.com/pymedphys/pymedphys/blob/398d741427843097e73092acc22de0460d238c4d/lib/pymedphys/tests/dicom/test_dose.py#L97-L206) employs option 2 and 3. I'll deal with each separately:

   - `test_sum_doses_in_datasets()` employs options 2 as follows: It begins by creating two `ndarrays` that will be used as dose grids. It then creates a dictionary that will be used as a template to create two `pydicom dataset`s. These datasets are subsequently created using `dicom_dataset_from_dict()` and then one of each of the aforementioned dose grids is added to these datasets, effectivel;y creating two usable RTDOSE datasets (_not_ files). Tests (checks for assertions) are then run using these datasets.

   - Many of the "subtests"/assertions in `test_sum_doses_in_datasets()` employ option 3. That is, they take existing datasets, make a modification to them, and then run a useful test on those modified datasets. For example, pay attention to lines [180-184](https://github.com/pymedphys/pymedphys/blob/398d741427843097e73092acc22de0460d238c4d/lib/pymedphys/tests/dicom/test_dose.py#L180-L184). This subtest is designed to ensure that `test_sum_doses_in_datasets()` will fail if either of the DICOM datasets supplied to it are not RTDOSE files. We _could_ create a new DICOM dataset that has the wrong modality, but there are already two existing datasets assessible to the test: `ds1` and `ds2`. So instead, the subtest simulates an invalid modality by simply altering the modality of one of the existing datsets, ds2.

-------------------------

I don't think it's the end of the world if you'd prefer to opt for option 1, especially if the files you've created are small. But if you're up for it, I really do think it would be useful for you (both for closer-to-optimal test design for PyMedPhys and also perhaps for your own experience) to give option 2/3 a go.

**Comment by Matthew-Jennings** [comment]
> @guanfada, if you could upload those files to https://github.com/pymedphys/data the same way as you did previously. Then you need to add the URL of the commit hash pin of the file upload over at the following file:

Oh, I haven't seen this!

**Comment by Matthew-Jennings** [comment]
One final point, we have _existing_ FFS data that would likely suit.

**Comment by SimonBiggs** [comment]
> @SimonBiggs, would you agree with my points above or am I missing something?

I think you've overviewed the options perfectly :slightly_smiling_face:. I wonder if there might be value in creating a contributor FAQ in the docs where we just link to historical GitHub comments like these? They would provide a great reference...

I'm happy for you to guide @guanfada the way you think would be most appropriate :slightly_smiling_face:.

> Oh, I haven't seen this!

Yeah, I'm no longer asking people to upload to zenodo. Too much friction. And @guanfada has already gone through the data repo step before. And by using the URL that links to the commit hash there is nothing lost wrt to the previous zenodo approach.

**Comment by guanfada** [comment]
@Matthew-Jennings @SimonBiggs 
  "RD.TBB_water_feet_first.dcm": "https://github.com/pymedphys/data/raw/036024218650eb5df62a04f2673b83375e8804b5/RD.TBB_water_feet_first.dcm"
  "RD.TBC_water_feet_first.dcm": "https://github.com/pymedphys/data/raw/036024218650eb5df62a04f2673b83375e8804b5/RD.TBB_water_feet_first.dcm" 
have been added to pymedphys/lib/pymedphys/_data/urls.json

**Comment by SimonBiggs** [comment]
Make sure you submit a pull request so that your changes can be merged into the main branch:

https://github.com/pymedphys/pymedphys/blob/main/lib/pymedphys/_data/urls.json

**Comment by Matthew-Jennings** [comment]
> @Matthew-Jennings @SimonBiggs "RD.TBB_water_feet_first.dcm": "https://github.com/pymedphys/data/raw/036024218650eb5df62a04f2673b83375e8804b5/RD.TBB_water_feet_first.dcm" "RD.TBC_water_feet_first.dcm": "https://github.com/pymedphys/data/raw/036024218650eb5df62a04f2673b83375e8804b5/RD.TBB_water_feet_first.dcm" have been added to pymedphys/lib/pymedphys/_data/urls.json

Okay, I can see that the files have been uploaded and added to `urls.json`. Now it's time to write the test!

How would you like to proceed? I'm happy to arrange for a videocall "pair programming" session, but I suspect that you'll already be able to make significant progress independently. To that end, I would suggest that you:

1. create and checkout a new local branch of `pymedphys` on your workstation
2. add a new skeleton test function to [`test_gamma_shell.py`](https://github.com/pymedphys/pymedphys/blob/main/lib/pymedphys/tests/gamma/test_gamma_shell.py) (just a function definition is enough to start, but feel free to add more. You'll need to add the line `pass` underneath the function definition for Python to be "happy" with an "empty" function.) 
3. commit and push these changes to Github
4. Create a new pull request (we'll continue discussions there as needed)
