### ISSUE TITLE
Move Pinnacle out of Experimental?

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1796]
Hi @pchlap,

How feasible would it be for the pinnacle module to be moved out of experimental?

**Comment by pchlap** [comment]
Hi @SimonBiggs,

We could easily drop the Pinnacle module out of experimental and into the main library. If we do that it's really important to have the tool be really noisy about that it is not to be used for any type of clinical work (and for research only). Especially because the RTPLAN export feature doesn't really work and I don't think anyone really has the motivation to get that working.

What do you think?

**Comment by SimonBiggs** [comment]
> What do you think?

Yup. Is anyone using the RTPLAN export feature?

**Comment by pchlap** [comment]
> > What do you think?
> 
> Yup. Is anyone using the RTPLAN export feature?

The only thing its really useful for is to make sure we can maintain that linkage between the RTSTRUCT -> RTPLAN -> RTDOSE... If the RTPLAN wasn't to be generated at all the only way to link them would be using the frame of reference which would often be ambiguous due to multiple structure sets floating around in the same frame of refernece.

**Comment by SimonBiggs** [comment]
@pchlap, what do you think the best path forward is?

**Comment by sjswerdloff** [comment]
There is a way to directly reference the RT Structure Set from the RT Dose, if you encode the RT DVH module:
https://dicom.innolitics.com/ciods/rt-dose/rt-dvh/300c0060
The reference to the plan is still required for the treatment planning scenario, and IMHO it makes a lot of sense to know the plan that was used to calculate the Dose.
The RT DVH module:
"...may supplement dose data in the [RT Dose Module](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.8.3.html#sect_C.8.8.3) and/or [RT Dose ROI Module](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.8.7.html#sect_C.8.8.7), or it may be present in the absence of other dose data."

So you can have your RT Dose contain the "pixel data" (dose voxels) and include just enough RT DVH to give you a place to put the referenced RT Structure Set.

I haven't checked to see what the intended use cases are, but I thought the above might be useful for some situations

**Comment by pchlap** [comment]
Thanks @sjswerdloff, this is useful.

So I suppose we could disable the generation of the RTPLAN entirely and adjust the RTDOSE object so that it links to the RTSTRUCT object like this. If we were to do this, would we be happy to just pull this module out of experimental and into the main library?

Note that I would never recommend this module be used in a clinical scenario. So I would ensure we keep all disclaimers indicating that this is intended for research purposes only. Given that we would make sure this would be sufficiently noisy to the user could we consider just lifting and shifting as is (RTPLAN included)?

**Comment by SimonBiggs** [comment]
@pchlap, I'm happy to run with your preference here.

**Comment by pchlap** [comment]
OK great, I think it would be least disruptive to those that are using it to just move it out of experimental as is. I can aim to put in a PR for this on Tuesday (heading to ESTRO on Wednesday so busy times at the moment).

One question I have is can we provide a useful error message when users try to import from the experimental module after it's removed? Do you have some ideas on how to best manage that? Is this the only module being moved out of experimental and into the main library?

**Comment by SimonBiggs** [comment]
I have a deprecation helper already in pymedphys which stands in for the old package, makes it still work when imported from its old location, and presents a deprecation message that informa the user of the new location.

**Comment by pchlap** [comment]
> I have a deprecation helper already in pymedphys which stands in for the old package, makes it still work when imported from its old location, and presents a deprecation message that informa the user of the new location.

That's awesome, perfect. OK will aim to have a PR in for you early next week.
