### ISSUE TITLE
Create a binary with pyinstaller

### ISSUE THREAD

**Issue by ArthurRochette** [pymedphys/pymedphys#1808]
Hello, I just want to build a binary from my script. But with this CLI command i got this error : No such file or directory : 'C:/.../Temp/_MEI85602/pymedphys/_imports/imports.py. 
I checked with my file explorer but the folder _MEI85602 doesn't exists .
I don't know if it's an error with pymedphys or i just made an error :/ 

PS: im using the command : pyinstaller main.py --collect-submodules pydicom --onefile --hidden-import pymedphys

**Comment by SimonBiggs** [comment]
Hi @ArthurRochette,

 Unfortunately I'm not immediately sure regarding this issue with pyinstaller. @Matthew-Jennings, you've played with that library a bit in the past, might you be able to lend @ArthurRochette a hand?

**Comment by Matthew-Jennings** [comment]
Hi @ArthurRochette!

`pyinstaller` is a wonderful tool, but it's a complex beast, and on previous occasions I've had to spend many days to get it correctly configured. A few things I'd recommend to start:

- Use `onedir` instead of `onefile`. `onefile` typically results in very slow app starting times, since all of the libraries have to be unpacked into a temporary directory anyway.
  - This might solve your specific issue.
- When you ran your command, pyinstaller should have created a .spec file. I suggest, for subsequent attempts to build with pyinstaller, edit this .specfile with your preferred configs and and run `pyinstaller main.spec`. This makes it easier to, say, add hidden imports and point directly to `.dll` files that `pyinstaller` usually cannot find unguided.
  - You never raised `.dll` gathering as an issue, but I suspect it will be given `pymedphys`' dependencies.
  - Read how to use specfiles (here)[https://pyinstaller.org/en/stable/spec-files.html].
 
Start with those and let me know how you go.

**Comment by ArthurRochette** [comment]
Hi @Matthew-Jennings thx for the help,
as you predict it --onedir does the trick, after the compilation I just copy/paste the pymedphys folder (from my python env) next to my binary and tadaa. 
Thx again for the help.

Best regards !
