### ISSUE TITLE
ds vs dataset

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#186]
:) just to bring this up:

https://pydicom.github.io/pydicom/stable/ref_guide.html#file-reading-parsing

It seems `ds` isn't an ubiquitous standard :)

**Comment by SimonBiggs** [comment]
...not sure how strong that statement is though when it is contradicted by scrolling down a little though :)

**Comment by Centrus007** [comment]
I'd chalk that up to a typo, old boy

**Comment by Centrus007** [comment]
Or a relic of old documentation written prior to adopting `ds`?

**Comment by SimonBiggs** [comment]
Hehe, yeah, the gitlens timestamp on that bit of logic is quite old.

Selective focus :)

**Comment by Centrus007** [comment]
If it bothers you enough, I'm honestly not particularly against `dataset` vs. `ds`. My preference for `ds` is a mild one at best - I just value convention.

With that in mind, we'll need a convention for our custom DICOM objects! I was kinda thinking the following:

- `dcm` for `DicomBase`
- `rtdose` or `dcmdose` for `DicomDose`
- `rtplan` or `dcmplan` for `DicomPlan` (if implemented)
- `rtstruct` or `dcmstruct` for `DicomStruct` (if implemented)
- `dcmct` for `DicomCT` (if implemented)

etc.

Maintaining the `dcm` prefix rather than `rt` seems more sensible, now I look back. And it's a nice little trouble to (y)our old convention :)

**Comment by SimonBiggs** [comment]
Do you mean when running `variable = DicomBase.from_file(filepath)`?

If that's the case my preference would be:

```python
dicom_base = DicomBase()
dicom_dose = DicomDose()
dicom_plan = DicomPlan()
dicom_struct = DicomStruct()
dicom_CT = DicomCT()
```

**Comment by Centrus007** [comment]
Yes, or `variable = DicomBase(ds)`

Those are fine too. They're starting to stretch my preference for shorter *standard* names though, because as soon as you start getting descriptive about specific instances, we get into poor-readability terriroty. E.g. imagine:

`dicom_dose_evaluation` or `dicom_struct_anonymised`. Uuuugggggh.

`dcmdose_eval` is much nicer to work with, and hardly less readable...

**Comment by SimonBiggs** [comment]
Fair point :)

**Comment by SimonBiggs** [comment]
This is slowly being solved organically.
