### ISSUE TITLE
0.8.x

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#191]
@SimonBiggs, what would you like to see in an 0.8.x release?

I was wondering whether you could guide me through your process (however rough)? It would be nice to be able to independently release (e.g. for urgent bugfixes, etc.) if you're away

**Comment by SimonBiggs** [comment]
Yup, how about we get you to do it with me on video call?

This one will be a case where we need to implement quite a bit.

For a 0.8.x release we need a block of time to sort out setting up all the
new packages on pypi and conda-forge. Before which we have narrowed down on
some good names. And then we do it. :).

**Comment by Centrus007** [comment]
> Yup, how about we get you to do it with me on video call?

Sounds great!

**Comment by SimonBiggs** [comment]
Actually, we should do this sooner rather than later. I think we should change the names to something we're happy with before I do the dependency tree things. It won't be too hard to change names using VSCode's find and replace tool + verifying tests aren't broken.

I think we need to sort out name changes for `pymedphys-shapes`, `pymedphys-numerics`, `pymedphys-wrappers`, and change `pymedphys-sql` --> `pymedphys-databases`.

Once we've sorted that, let's make the release :).

**Comment by Centrus007** [comment]
Okay. First iteration:

`shapes` --> `electronfactors`, since there's nothing else in there yet anyway? Or maybe `rtplanning`?
'numerics` --> maybe `geometry` and move `deliverydata` into `logfiles`? Not sure on this one. Or perhaps 'coordsandscales` (tribute to IEC)?
`wrappers` -- > separate into own packages?

**Comment by SimonBiggs** [comment]
I expect `DeliveryData` to be quite a fundamental data object in the future. For example, at some point I would expect an RTDicom object to be able to export a `DeliveryData` object. But certainly `coordsandscales` fits quite well, as `DeliveryData` is essentially MLC positions, gantry angles, etc. 

With `rtplanning`, I can envisage other `rtplanning` modules that shouldn't ever need to go near `shapely`. Maybe just `electronfactors` is best.

`wrappers`, yup, for now, split into the two packages for the modules that make them up.

**Comment by SimonBiggs** [comment]
On pypi by the way we can make release candidate releases for example, see the following:

https://pypi.org/project/pymedphys/0.5.0rc1/#history

I propose we do a multi-staged roll out. First step would be to release everything as release candidates. Then we need to step through our installation docs and check that everything runs as expected. Then we prep for a proper release.

**Comment by SimonBiggs** [comment]
Can we use the following for the remote desktop?

https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp?hl=en

**Comment by SimonBiggs** [comment]
@Centrus007

**Comment by SimonBiggs** [comment]
@Centrus007

**Comment by SimonBiggs** [comment]
@Centrus007 https://remotedesktop.google.com/access

**Comment by SimonBiggs** [comment]
@Centrus007 you'll want to click "get support":

![image](https://user-images.githubusercontent.com/6559099/56576424-acb92900-660b-11e9-813d-c0334e30e3c0.png)

**Comment by SimonBiggs** [comment]
![image](https://user-images.githubusercontent.com/6559099/56586332-e184aa80-6622-11e9-8ea6-eaf4341b3e41.png)

https://xkcd.com/2140/

**Comment by Centrus007** [comment]
:heart:
