### ISSUE TITLE
Developer setup guidelines no longer work after the big split (#171)

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#192]
This little snippet no longer works:

```bash
λ conda install pymedphys --only-deps
...
λ pip install -e .
Obtaining file:///C:/Users/mjenni03/PythonProjects/pymedphys
Collecting pymedphys_analysis (from pymedphys==0.8.0.dev0)
  Could not find a version that satisfies the requirement pymedphys_analysis (from pymedphys==0.8.0.dev0) (from versions: )
No matching distribution found for pymedphys_analysis (from pymedphys==0.8.0.dev0)
```

Should we replace `pip install -e .` with `yarn`?

Also, I was thinking it might be nice to write up a simple batch script for users to run? I think that roughly the entire second half of the process could be batched...

**Comment by SimonBiggs** [comment]
For now we can certainly say yarn, but I'm not yet sold on that being the
way we lock in doing it long term.

For example we might be able to have something within setup.py trigger if a
certain tag is passed to pip, and that could trigger installing everything
else.

At the moment we have the installation dependency resolution process copied
in 4 different places (tox.ini for testing, requirement-docs.txt for
readthedocs, package.json dependency structure for yarn + lerna,
install_requires dependency structure). We need to reduce that down to one.
Given that I've just found out that readthedocs doesn't play nice with yarn
I suspect the "one" we pick might be forced on us by compatibility with
readthedocs.

An idea that I am converging on is an automatically created
requirements.txt file that details the dependency order created from the
dependency tree utility.

That way the install process would look like:

pip install -r requirement-development.txt

Instead of:

yarn

That might be more explicit and familiar with python developers anyway.

**Comment by Centrus007** [comment]
Okay. Shall we prioritise that in advance of 0.8? Or go with `yarn` for now?

**Comment by SimonBiggs** [comment]
That requirements file is currently there, we just need to add `-e .` at
the end of it and it should work.

**Comment by Centrus007** [comment]
Ah, so it's just not automatically created yet?

**Comment by SimonBiggs** [comment]
> Ah, so it's just not automatically created yet?

not yet, nope.

**Comment by mchamberland** [comment]
Sooo.... how should I install the bleeding edge developer version right now? Running 'pip install -e .' results in an error because there is no setup.py file.

**Comment by SimonBiggs** [comment]
:)

Install yarn:
https://yarnpkg.com/lang/en/docs/install/#debian-stable

Then run `yarn bootstrap`.

For future reference we have been keeping the following document up to date:
https://docs.pymedphys.com/developer/contributing.html#install-the-development-version-of-pymedphys

We do really need a summary though at the top that says something like:

"For those who know what they're doing, to install PyMedPhys from source run `yarn bootstrap` in the root directory of the repo"

**Comment by SimonBiggs** [comment]
I'm on my phone at the moment, if you wanted to throw that (/something worded better) in a pull request that'd be awesome :)

**Comment by SimonBiggs** [comment]
I'm still torn about using yarn to help install things long term. I suppose it doesn't hurt too much. Just have to improve the documentation...

**Comment by SimonBiggs** [comment]
https://github.com/pymedphys/pymedphys/issues/435

**Comment by maneetgoyal** [comment]
@SimonBiggs Going back into this project's history, at one point you used lerna + yarn before switching to poetry (in 0.12.x). Could you please give any reasons for doing it? I have a lerna + yarn workspace based JS/TS monorepo ready. Now I want to include some Python "packages" as well in that same monorepo. Was thinking of using the same approach you picked earlier. So trying to figure out any possible downsides before writing too much code.

**Comment by SimonBiggs** [comment]
Hi @maneetgoyal,

It actually all worked quite nicely. The only downside is that it was "non-standard" for Python developers. Someone who develops in Python has expectations about what they can do in a repo and how they can get started. I found I was just making it a little bit harder than was necessary for newcomers to PyMedPhys who had familiarity with the Python ecosystem.

Certainly if your repo is JavaScript first with a dash of Python, then my previous approach would work quite nicely I expect. :)..

**Comment by SimonBiggs** [comment]
I should add, that the big need for us, for having a Python multipack age monorepo was so that users could select different sections of PyMedPhys and be able to install it with minimal dependencies. For Python I actually found a tidier way to achieve this with out the need for multiple packages. And that was by using a vendored fork of apipkg which allows for optional Python imports. External packages are able to be imported at the top level of a file, but they only actually end up being imported by Python just-in-time. This removes some of the fail fast benefits that come from having import errors raise right away, but it gains the ability to run with no dependencies for parts of the code base that don't need any:

https://github.com/pymedphys/pymedphys/blob/c3569cdd2e1114ae17b165e2aa6bdf8bba2214ee/lib/pymedphys/_imports/__init__.py

As such, we no longer needed many sub-packages, and instead achieved the flexibility of a no-depebdency install through optional import logic. So, away went the monorepo.
