### ISSUE TITLE
pymedphys.com looks broken

### ISSUE THREAD

**Issue by Centrus007** [pymedphys/pymedphys#342]
https://pymedphys.com/ - @SimonBiggs

**Comment by SimonBiggs** [comment]
See https://github.com/pymedphys/pymedphys/pull/335#discussion_r286918867

**Comment by SimonBiggs** [comment]
I realised within Netlify I can tell it to revert to a previous build:

![image](https://user-images.githubusercontent.com/6559099/58256097-b1f7c800-7db1-11e9-983b-c51188fbea36.png)

I've done that now. So, master is still broken for its docs. But the website is back up and running.

**Comment by SimonBiggs** [comment]
@Centrus007 also, you've been invited to help manage that site:

![image](https://user-images.githubusercontent.com/6559099/58256508-7a3d5000-7db2-11e9-9390-a7b7513e8227.png)

In case this happens again and I am not available, would you be able to accept that invite so that you are free to revert website builds if ever needed?

**Comment by Centrus007** [comment]
> In case this happens again and I am not available, would you be able to accept that invite so that you are free to revert website builds if ever needed?

Done! Sorry I missed that.

**Comment by SimonBiggs** [comment]
> > In case this happens again and I am not available, would you be able to accept that invite so that you are free to revert website builds if ever needed?
> 
> Done! Sorry I missed that.

:) Thanks :), all good :)
