### ISSUE TITLE
Add option to anonymise DICOM UIDs

### ISSUE THREAD

**Issue by Matthew-Jennings** [pymedphys/pymedphys#372]
Suggested by @sykesjonr

Need to create valid UIDs with appropriate linking to maintain compatibility with various commercial systems. Probably best mediated through our planned DICOM study object?

**Comment by SimonBiggs** [comment]
Yup certainly. When you say anonymise the UIDs do you mean "reroll them"
based on the PyMedPhys base UID? And then appropriately propegate the
linking UIDs to each DICOM study set that is linked?

I could think how to do it quite neatly before we have sorted out the
objects... But it probably would be most tidy as part of the full
DicomCollection object...

**Comment by Centrus007** [comment]
> When you say anonymise the UIDs do you mean "reroll them" based on the PyMedPhys base UID?And then appropriately propegate the linking UIDs to each DICOM study set that is linked?

Exactly, yes.

> I could think how to do it quite neatly before we have sorted out the objects... But it probably would be most tidy as part of the full DicomCollection object...

What would be your preference? A functional implementation or OOP first?

**Comment by SimonBiggs** [comment]
I'm not sure.

The design of the Delivery object kinda just fell into my lap. ... I'm
kinda waiting for that to happen with the DICOM object...

Not sure if it's the best way to do it, maybe solve it functionally and
that might make it clear how best to have the object work?

What do you think?

**Comment by Matthew-Jennings** [comment]
I think to get something useful initially, maybe we just replace UIDs with our own generated ones on a single file basis, note that this will break links with other DICOM files in the Study/Series and note that we intend to support Study/Series-wide anonymisation in the future?

**Comment by SimonBiggs** [comment]
My preference honestly is to support it appropriately with file hashing from the get go. We're not in a rush to anonymise UIDs are we?

**Comment by Matthew-Jennings** [comment]
> My preference honestly is to support it appropriately with file hashing from the get go. We're not in a rush to anonymise UIDs are we?

Maybe a little. We're currently non-compliant (whose definition UID clearance) and, in theory, could have plenty of users. Especially since it's in the app.

**Comment by SimonBiggs** [comment]
Kk, as in if we change the DICOM file we need to update the UIDs?

I'd really like our UIDs to be deterministic. As in this DICOM file always
produces such n such UID.

An SHA hash of the file contents, appending then a transformation into the
required UID format shouldn't be too difficult.

**Comment by Matthew-Jennings** [comment]
> Kk, as in if we change the DICOM file we need to update the UIDs?

As in, if we claim DICOM file anonymisation, we need to remove UIDs since they can threotically be traced back to a given patient.

**Comment by SimonBiggs** [comment]
Is that really the aim of anonymisation?

If you have access to UIDs to patient maps don't you have access to the
original files also?

**Comment by Matthew-Jennings** [comment]
> Is that really the aim of anonymisation?

Yes.

> If you have access to UIDs to patient maps don't you have access to the
original files also?

The user doing the anonymisation does, yes. But the users to whom any anonymised files are subsequently sent do (and should) **not**.

**Comment by Matthew-Jennings** [comment]
I recommend you give DICOM Supplement 142 a browse. We really should be following it.

Other things that come to mind is that we probably ought to remove the parameters `replace_values` and `delete_private_tags`, since standard anonymisation requires removal of all private tags and gives specific instructions for replacement/removal of elements.

We could always implement a `tags_to_leave_unchanged` to pair with `keywords_to_leave_unchanged` - the former possibly being required for private tags. And if the user wants custom values elsewhere, they can just include 1 or 2 lines that use `pydicom`

**Comment by SimonBiggs** [comment]
If there is a documented standard of how to anonymise then we should follow
that standard.

**Comment by SimonBiggs** [comment]
...we really can't break connections however. When a whole directory is passed at once we need to create a UID mapping so that all connected DICOM files that are within a directory have their appropriate connections propagated through with the updated UIDs.

**Comment by SimonBiggs** [comment]
When a single DICOM file is passed I believe we need a warning to be displayed that private tags are being removed and UIDs are being reassigned.

Maybe there should be a "anonymisation results" file created. It would be created in the directory the command was run, and it would contain within it the UID map json. This map would then be read for subsequent anonymisation undergone so that should a DICOM file contain a connection to one of those UIDs in the map it knows to look up the map.

And potentially, the anonymiser should not initially anonymise if it has a UID link that doesn't exist within the map.

Potentially it could run this way, have a list of DICOM files to anonymise. If a file has a link that is not in the map move that file to the end of the list and deal with it later. As files are anonymised their new UID will be added to the map, so that by the time the files at the end of the list are reached the mapping will now exist.

An optional parameter of --remove_dicom_links could be passed to just freely anonymise and remove any UID links explicitly. That way, if the user really doesn't care about links then those links can be removed (as they wouldn't be "anonymised" themselves)

**Comment by Matthew-Jennings** [comment]
> ...we really can't break connections however. When a whole directory is passed at once we need to create a UID mapping so that all connected DICOM files that are within a directory have their appropriate connections propagated through with the updated UIDs.

I agree with this as an eventual solution. And I think I'm open to keeping UIDs non-anonymised for the time being until we implement that solution.

> When a single DICOM file is passed I believe we need a warning to be displayed that private tags are being removed and UIDs are being reassigned.

Happy to warn, but maybe overkill to permit `delete_private_tags=False`.

> Maybe there should be a "anonymisation results" file created. It would be created in the directory the command was run, and it would contain within it the UID map json. This map would then be read for subsequent anonymisation undergone so that should a DICOM file contain a connection to one of those UIDs in the map it knows to look up the map.

I think this gets messy. And although lovely if we can make it tidily work, I'd point out that (once we're compliant), we're already well past the capability of any anonymiser I've ever used.

**Comment by Matthew-Jennings** [comment]
> And potentially, the anonymiser should not initially anonymise if it has a UID link that doesn't exist within the map.

I don't like this. Users will very often deliberately only wish to deal with a subset of a study. This prevents them from doing so (and is not at all how existing anonymisers work).

**Comment by Matthew-Jennings** [comment]
> An optional parameter of --remove_dicom_links could be passed to just freely anonymise and remove any UID links explicitly. That way, if the user really doesn't care about links then those links can be removed (as they wouldn't be "anonymised" themselves)

At first I thought this was unnecessary, but now I actually think a `remove_links` parameter would be very useful indeed! Links themselves can be a major bugbear for systems that enforce single copies of a given DICOM.

**Comment by sykesjonr** [comment]
I'm guessing you are all over this but just make sure frame of reference
UID is fixed across all series that have the same frame of ref UID in the
originals. Structure file is the worst to de-identify as every contour
references the UID of the slice it was contoured on.

An alternative to hashing is to use the system clock down to ms and then
add a short random number. I'm sure this is what some manufacturers do. But
hashing maybe more robust?

Jonathan


Jonathan Sykes
0456 072 175

**Comment by SimonBiggs** [comment]
A large benefit of hashing is that should a DICOM file be made with exactly
the same contents and data it will always result in the same UID. Meaning
there is a guarantee that if two DICOM files are the same, even if they
were regenerated at different times, you can see they are they same by
their UIDs being equal to each other.

**Comment by SimonBiggs** [comment]
> I recommend you give DICOM Supplement 142 a browse. We really should be following it.

I have just had a cursory browse. Turns out there is a valid option to anonymise with a "Retain UIDs profile".

**Comment by sykesjonr** [comment]
Sounds like a good option then.

**Comment by SimonBiggs** [comment]
@sykesjonr, just a heads up, given the public nature of this issues mailing list I have edited your posts to remove your phone number, and also deleted the corresponding revision history.

**Comment by SimonBiggs** [comment]
@Matthew-Jennings can you provide me a use case example where the "Retain UIDs profile" detailed within DICOM Supplement 142 would be unusable.

**Comment by sykesjonr** [comment]
Thanks for pointing me to this document. It will take a bit of digesting.
When an image is exported from a system, de-identified and then used for
research in another system the requirement to replace UIDs is reduced as
the risk of traceability back to the source is negligible and would require
security access i.e. only a professional within the system should be able
to trace it back and find the source data records. However, we do quite a
lot of research in our clinical system. In our case, with Aria/Eclipse you
cannot re-import images with the same UID into another patient. FOr this
reason I have found that I have needed to replace UIDs. To do this I have
been using MIM Maestro.  I did try using the Orthanc DICOM  software but
for some reason that I have not yet traced, the images will not import into
Aria. Mind you, Aria/Eclipse DICOM import is temperamental and not easy to
use.

Jonathan

**Comment by SimonBiggs** [comment]
Ahh, so what you are after is not necessarily something that needs to be tied closely to an anonymisation function, but instead it could be its own standalone tool where you pass it a directory of DICOM files and it randomises the UIDs while also appropriately retaining the UID links between all the files that are within the directory.

For this purpose a hash isn't really desirable as you might want to reroll the UIDs to create multiple duplicate sets with the same contents but different UIDs.

Would something like that meet your aim?

I could imagine it might be run from a command line like the following:

```bash
pymedphys randomise_dicom_uids input_directory output directory
```

**Comment by SimonBiggs** [comment]
I would imagine it would also be improved by having another CLI which would bulk edit certain keywords within DICOM files found within a directory:

```bash
pymedphys randomise_dicom_uids input_directory intermediate_directory
pymedphys replace_dicom_items --patient_name "SMITH^JOE" --patient_id 12345 intermediate_directory output_directory
```

**Comment by Matthew-Jennings** [comment]
> Ahh, so what you are after is not necessarily something that needs to be tied closely to an anonymisation function, but instead it could be its own standalone tool where you pass it a directory of DICOM files and it randomises the UIDs while also appropriately retaining the UID links between all the files that are within the directory.
> 
> For this purpose a hash isn't really desirable as you might want to reroll the UIDs to create multiple duplicate sets with the same contents but different UIDs.
> 
> Would something like that meet your aim?

I'll let @sykesjonr answer your question directly, but I'll instead ask another one:

Perhaps a `hash` is still doable if `randomise_dicom_uids()` also makes a very slight edit to (or perhaps adds) a non-UID element? If the element is well-chosen, we might hit the sweet spot of both "strictly different DICOM files that warrant different hashes" and "practically identical DICOM files from the user perspective"?

**Comment by SimonBiggs** [comment]
> makes a very slight edit to

What about simply the following:

```
pymedphys replace_dicom_items --patient_name "SMITH^JOE" --patient_id 12345 intermediate_directory output_directory
```

If it followed the hash UID, that would also result in "randomised" UIDs. I would imagine for each dummy set it would be reasonable to have a different patient_id ...

**Comment by sykesjonr** [comment]
I think you would always want to change the UIDs at the same time as anonymising so that way there would always be changes to the files for a hash to work. The bulk edit is also a useful feature so that you can e.g. change the treatment machine name to one that is in a test database or heaven for bid there is some DICOM field that your anonymiser does not know about and you want to clean.

**Comment by SimonBiggs** [comment]
Hi @sykesjonr,

Is the new `--psuedo` flag on the `pymedphys experimental dicom anonymise` CLI solve this issue?

https://docs.pymedphys.com/ref/cli/pseudonymisation.html

See the release notes:
https://docs.pymedphys.com/release-notes.html#new-features-1

Thanks @sjswerdloff for the PRs :).

**Comment by sjswerdloff** [comment]
The experimental pseudonymisation (--pseudo) hashes the existing UID, then appends a big integer representation of it to the PyMedPhys Org Root, and consumes all of the remaining (out of 64) characters available.   So the relationships between connected sets of data should be retained.  Clashing (hash collision) is possible, but very unlikely.  

It does at least obfuscate things that are often put in UIDs that in theory shouldn't be there (like date information, which is incredibly useful for practical purposes when data gets written to file, on a file system, with the UID in the file name.  It's that practicality that makes it so tempting to create them that way).

But the (current) implementation of pseudonymisation won't provide a direct means of creating additional copies of the same data with *different* pseudonymised UIDs.
If you want to create another copy of a connected set of data, you could run pseudonymisation against the (already) pseudonymised data.  "Turtles all the way down".  The patient level information will be altered as well, so it won't provide "a separate copy for the same 'patient'"

If you really want an exact copy of the data with the exception of the UIDs, that's a separate problem.
When I do something like that by hand for a highly constrained/local sandbox, as long as the UID isn't already 63+ characters, I just append .1 (and then .2, .3, .4 up to .9 although one could go higher if one has the character space).
It's not a good approach in general unless one owns the org root and knows that those additional digits won't appear for other "legit" data.  It's not practical to do this by hand for a large connected set of data (like CT and an RT Structure Set referencing those CT... I know the pain...).
The use case is real.

A potential approach is to allow for the Org Root used by pseudonymisation to vary based on "something" (e.g. an environment variable), and in between "copies" to alter the value used for the Org Root (e.g. append .1, .2 etc. to the PyMedPhys Org Root).  You increase the likelihood of clashing because you have fewer characters available, but it's still pretty unlikely.
Having the Org Root of the pseudonymised UIDs be "configurable" by some mechanism is an enhancement to the pseudonymisation implementation that has been discussed.  It makes a lot of sense for a user who has their own Org Root (e.g. a commercial entity, or a different Open Source project that has obtained one).  The mechanism I had considered was an environment variable.  But pymedphys also has a nice "configuration" facility (via a .toml file?).
A related alternative is providing configurable salt to the hash.  And then varying the salt between runs against the same data.  I don't know how badly that would affect the likelihood of a clash (hash collision).  Having (configurable) salt also makes it harder for someone to perform a "dictionary" attack against the hashed values.

**Comment by sjswerdloff** [comment]
Oh... the refactoring of anonymise allows a programmer to extend the list of identifying keywords (more generally, to provide their own) and pass that in to the higher level anonymise functions.  For that situation mentioned where there is a DICOM field the anonymiser doesn't know about.
