### ISSUE TITLE
Tests can be written within notebooks

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#424]
https://nbviewer.jupyter.org/github/deathbeds/deathbeds.github.io/blob/master/deathbeds/2018-07-31-Testing-notebooks.ipynb

To promote testing in a comfortable format, tests can be written within notebooks and discoverable via pytest.

**Comment by SimonBiggs** [comment]
https://github.com/deathbeds/importnb#importnb-for-testing

**Comment by SimonBiggs** [comment]
Another related tool https://github.com/computationalmodelling/nbval

**Comment by SimonBiggs** [comment]
... certainly not the best as the default way of writing tests. But it would certainly fit a subset of cases well.

**Comment by Matthew-Jennings** [comment]
To be perfectly honest, I'm still a fan of moving *away* from Jupyter notebooks, rather than towards... so I'm not super excited by something like this. 😊

To cater to those like yourself who prefer Jupyter notebook-like functionality for tinkering and early development, VS Code has a lovely way of providing JN-like cells using the `#%%` command. I invite you to try it. Is it a suitable compromise?

**Comment by SimonBiggs** [comment]
Hehe, nope, not a suitable compromise. Jupyter Notebooks are certainly good for prototyping. They do have a place.
