### ISSUE TITLE
Anonymise DICOM CLI

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#70]
Heya Matt,

I think it would be worth us having an anonymise DICOM CLI based off of your notebook.

One difference would be that it should probably make a top level directory that holds a duplicate directory structure to those that contain dicom files instead of dropping an anon directory in each directory.

Just wanted to write it here so we don't forget.

**Comment by Centrus007** [comment]
I agree.

To be honest, I've actually made the following slight change to that notebook that I haven't yet added to the PyMedPhys repo:

I found it significantly more convenient to provide a root dir to the function but then do away with creating an entire new dir tree by instead just creating copies of all anonymised DICOM files with "anon" or similar prepended to their filenames. The anonymised copies just lay in the same dir as the source files.

It saves creating and preserving a directory structure that I actually found less convenient anyway. It is relatively straightforwrad to relocate the files afterwards because the prepended "anon" allows sorting by name to differentiate anonymised files quickly.

**Comment by Centrus007** [comment]
> LGTM :), I reckon I good addition along the line of this pull request would be that CLI as well as some tests of that CLI. As in a few simple dicom files made within the test, within the directory, a call of the CLI, and then a verification that the key tags have been removed.

> Maybe a dicom file can be made using the baseline dataset, have the CLI anonymise the baseline dataset, then have the test verify that the identifying tags and no others are replaced appropriately.

(@SimonBiggs, I copied the above from an about-to-close pull request to here so it doesn't get lost :) )

**Comment by Centrus007** [comment]
#Resolved by #222
