### ISSUE TITLE
Seriously consider swapping from Poetry to pip-toools

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#724]
@matthewdeancooper you mentioned the complexity of poetry may just make it not the right fit for us. Here is a toolkit that follows the unix philosophy of "do one thing and do it well":

https://medium.com/telnyx-engineering/rip-pipenv-tried-too-hard-do-what-you-need-with-pip-tools-d500edc161d4

Let me know what you think.

**Comment by SimonBiggs** [comment]
Here is a description of `pip-tools`. It hits the primary need of creating pinned and hashed packages:

https://github.com/jazzband/pip-tools#using-hashes

**Comment by matthewdeancooper** [comment]
Dependency management is not an area that i have much experience to add I'm afraid. Other than that more depends can equal more problems when using a bleeding edge distro.

However, I just tried a fresh install of pymedphys with poetry. After setting the python version to 3.7.5 (from 3.8) with pyenv, the poetry install was an easy one line cut and paste - and poetry is already packaged in the arch repo.

The build did fail with 3.8 but I believe that was due to the pymssql version (==1.4.1) required.

I think simplifying complexity is a great idea when it provides an obvious advantage - ie. minimalist cli tools are easy to grok, hack, debug, and chain together. 

I haven't contributed to enough python packages to have a good understanding of how common poetry is cf. pip-tools and/or the advantages of switching to something more minimal in this case. If the 'something else' would still require an install and isn't as common as poetry, then you could be adding a single-use dependency to the chain. Happy to discuss further.

**Comment by SimonBiggs** [comment]
Yeah, I think there are some good well founded thoughts there. I think, if we find `poetry` continues to cause a bumpy ride, then I'll swap it out. I might play around with `pip-tools` on another project and have them both in my tool belt in case a swap would be beneficial down the road.
