### ISSUE TITLE
My desire to make PyMedPhys a platform

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#830]
Hi @Matthew-Jennings,

I think this post below makes it clear as to why I am so focused on building a platform first, and then using that platform to build the application:

https://web.archive.org/web/20180101221909/https://plus.google.com/+RipRowan/posts/eVeouesvaVX

The key is, "there IS no perfect product for everyone" and to be successful, you need to allow people to extend your tool. To have the tool extension framework be polished, the very tool itself needs to be built with that tool extension framework. You need to eat your own dogfood so to speak.

I would argue, it is this very feature that has made ImageJ so successful in our field. It is this that has made ImageJ stand the test of time and age well.

**Comment by Matthew-Jennings** [comment]
One key question is: how many people are there out there who would build upon the platform? 

Is it worth it?

**Comment by jrkerns** [comment]
@SimonBiggs reading your issues is like my own personal feed haha, I love it. Interesting article. You may want to get insight from Aditya @bastula who made dicompyler extensible from the beginning. I'm sure he has some Lessons Learned.

**Comment by crcrewso** [comment]
If you're wanting to go down that road seriously, may I recommend that you optimize for [numba python](http://numba.pydata.org/) It looks to be the parallelization toolkit that numpy has settled on.

**Comment by SimonBiggs** [comment]
@jrkerns hehe about the feed :). Cheers for the pointer. @bastula, did you have some key pointers?

I am certainly orbiting around Streamlit + BlueprintJS with a built in extension manager allowing people to download the base PyMedPhys GUI, and then be presented with a package list that people can publish to themselves (likely via a tag on GitHub, much the same way JupyterLab does it).

I think an important must, from what I gather, is to eat one's own dogfood. As in, make the platform, then build all of my own functionality as an application on that platform. That way, while eating my own dogfood, I see the flaws in the platform itself.

**Comment by SimonBiggs** [comment]
Hi @crcrewso,

Great to see the new face :). Can you discuss what you mean by numba with respect to PyMedPhys as a platform?

**Comment by crcrewso** [comment]
@SimonBiggs Thank you. I found your work through @AndrewWAlexander and the pinnacle to dicom converter that was upstreamed a while back (thanks @pchlap ). 

Numba is a library that allows the developer to set up ahead-of-time compiling rules for improved performance, parallelization-safe and parallelization-unsafe flags on functions and other general niceties.  

So, lets say you have a function which, when python runs naively takes 100s, but after you run it a few times it drops to 10s, and is trivially parallelizable to 4 cores, which would take it to 2.5s. 

No lets say you have a system like QATrack that a user calls your function from inside that system. 

Well the first few times after a server restart restart the test is going to look like it's processing forever (> 1 minute), eventually dropping down to the 10s per calculation as the interpreter runs the cpython compiled version.  But if you forced it to be compiled then the user will always have a consistent experience of 2.5 s. 

I looked through a few of the ahead of time flags and Numba stood out with its numpy support. If you see a different way of accomplishing the same outcome I'd be happy to play with it too. 

Does that make any sense? It's not something necessary for functionality, but at scale it would help users extending your framework.

**Comment by SimonBiggs** [comment]
@crcrewso would you be able to create a new issue for this? It'd be exceptionally helpful if you could present some empirical results with line_profiler (https://ipython-books.github.io/43-profiling-your-code-line-by-line-with-line_profiler/) for a particular function which you would like to be running faster and have it detail what you are describing.

I could imagine MU Density, or Gamma, would be prime targets for having a speed up be desirable.

**Comment by bastula** [comment]
@SimonBiggs @jrkerns et al. Thanks for pinging me.

A few lessons learned from the dicompyler project:
- Choose a UI platform that can be easily extended and has good support and documentation
- Provide a venue for users to upload their own plugins or at least have standard code syntax & formatting so they can host it themselves
- Realize that a lot of medical physicists aren't programmers and you will be supporting not only onboarding to your project, but onboarding to Python (and even programming)
- If the project takes off, and is licensed liberally, expect forks and derivative works in forms of open source and closed source. This is a blessing and a curse, because you may find valuable contributors that can't (for legal or other reasons) or won't be willing to contribute back. On the other hand, you get the few gems that really want to help and not only write plugins but also want to help out on the main code base.

Tangent:
- We have a lot of great minds on this thread and there are also others. How can we come together (PyMedPhys + dicompyler + pylinac + pydicom + QATrack+ and I am sure others that I am forgetting) to do this under one umbrella? We have a lot of our own standalone projects but I would still like to see something unified like the rest of us. Working in silos (just like clinical practice sometimes) leads to a lot of repetition and duplication of efforts.

**Comment by SimonBiggs** [comment]
Regarding the tangent, I think a great way to start would be to purposefully bring together all who intend to design and build the platform (and subsequently build into the ecosystem of the platform itself), and have us as a group from the get go brainstorm and decide what we want it to be, what we want it to achieve, and what technologies we want to hone in on to achieve that.

That way, all these minds you reference have ownership from the beginning.

Potentially it is something that stands on its own, apart from anything that's gone before. Certainly designed so each of our projects can be readily utilised within the platform's ecosystem. If we go down that path then pymedphys would be its own repo designated to be a library only, and then the platform and it's ecosystem would be designed so that pydicom, dicompyler-core, pylinac, pymedphys, and any other medical physics pip installable libraries could be utilised within the platform.

Probably the first step is together to brainstorm a name for this platform and ecosystem as well as what we want it to become. I'm open to all sorts of names, but I think it's important that it is something that all those minds you list @bastula are a part of bringing it into existence. This issue is probably as good a place as any to brainstorm such a thing. And if the platform component isn't actually going to be within pymedphys, but another project altogether, then this issue can certainly be repurposed for said brainstorming.

@bastula what do you think? If you think that's a good idea... Then I propose we beginning pinging people via GitHub mentions into this issue and get this brainstorming rolling...

**Comment by SimonBiggs** [comment]
One of my key requirements I believe, is that whatever it is, it needs to be as easy to install as it is to install dicompyler (go to website, download .exe, run), and as easy to create plugins as it is to write a Streamlit app or a Jupyter Notebook.

**Comment by sjswerdloff** [comment]
So... What is the platform intended for?
Radonc?
Diagnostic and Radonc?
Is HL7/FHIR part of the intended stack?

I'm not dissing, it's a genuine question, because in the commercial space discovering your target after you've done the work is called pivoting.  And the other  word for it is failure, depending on the outcome.

Numba is gaining traction. So is Streamlit and the other packages mentioned.  Personally, I like to see a stable API before betting the farm.  Or else there is a lot of maintenance in keeping up, or alternatively getting stuck on an old version (at least that's relatively easy to enforce for ones own work, but downstream consumers can run into problems... The reason conda is so useful...) 

The perfect is the enemy of the good, and premature optimisation is something to be cautious about.  Obviously not my own wisdom but worth repeating. 

In keeping with the guidance I received recently, I suggest refactoring experimental and the cli to support plugins, along the lines of pluggable factory based on configuration, before taking on the world. 

Pydicom already seems to be an umbrella for other work (e.g. pydicom/DeID) 

Now, if the target is RadOnc I propose PyRO 
unless that's taken...

**Comment by BishopWolf** [comment]
I think you shall independise the platform functionalities from the calculation functionalities. Try to make a package for each of these modules independently
* DICOM Module
* Gamma Index
* MU Density
* Electron Cutout Factors
* Experimental Modules
Then use those packages as dependencies, if you put them together then your project will be crowded and users will need to install the whole thing to access just to gamma index for instance.

**Comment by SimonBiggs** [comment]
PyMedPhys itself is about an ~800kB and, the way it is set up, each module can run in such a way that only the dependencies for that part need to be installed. This is because under the hood, imported libraries only cause an import error when they're used, not when they're imported.

In the past pymedphys was split up into a range of packages. But the development overhead was large, and the barrier of entry to new developers was also large.

Are you able to see if installing pymedphys without any dependencies meets your needs?

**Comment by BishopWolf** [comment]
As a user of gamma_shell exclusively, I require no other module and no other dependencies. and with the --no-deps flag while installing I can solve my problems

**Comment by SimonBiggs** [comment]
Yup, my plan is to always make it that each part of pymedphys can be used independently of the dependencies needed for the other parts. Someone who knows what they're doing can install with no-deps, and others who just install it will get all the batteries included.

Also, the last problem dependency (pymssql) which struggles to install on MacOS will be removed in the near future anyway. So that should then be the last trouble dependency removed also.
