### ISSUE TITLE
Potential dependency conflicts between pymedphys and numpy

### ISSUE THREAD

**Issue by NeolithEra** [pymedphys/pymedphys#839]
Hi, as shown in the following full dependency graph of **_pymedphys_**, **_pymedphys_** requires **_numpy >=1.12,<2.0_**, **_pymedphys_** requires **_matplotlib *_** (**_matplotlib 3.2.1_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_matplotlib 3.2.1_** transitively introduces **_numpy >=1.11_**.

Obviously, there are multiple version constraints set for **_numpy_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_numpy 1.19.0rc1_** (i.e., the newest version satisfying constraint **_>=1.12,<2.0_**) is the actually installed version.

Although the first found package version **_numpy 1.19.0rc1_** just satisfies the later dependency constraint （**_numpy >=1.12,<2.0_**), such installed version is very close to the upper bound of the version constraint of numpy specified by **_matplotlib 3.2.1_**. 

Once **_matplotlib_** upgrades，its newest version will be installed, as **_pymedphys_** does not specify the upper bound of version constraint for **_matplotlib_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_matplotlib_** version introduces a higher version of **_numpy_**, violating its another version constraint **_>=1.12,<2.0_**.

According to the release history of matplotlib, it habitually upgrates Numpy in its recent releases. For instance, matplotlib #15645 upgrated Numpy’s constraint from **_>=1.11 to >=1.12_**, and matplotlib #15698 upgrated Numpy’s constraint from **_>=1.12 to >=1.15_**. 

As such, it is a warm warning of a potential dependency conflict issue for pymedphys.

### Dependency tree
```
pymedphys - 0.27.0
| +- attrs(install version:19.3.0 version range:*)
| +- cython(install version:3.0a1 version range:*)
| +- dbfread(install version:2.0.7 version range:*)
| +- imageio(install version:2.8.0 version range:*)
| | +- numpy(install version:1.19.0rc1 version range:*)
| | +- pillow(install version:7.1.1 version range:*)
| +- keyring(install version:21.2.0 version range:*)
| +- matplotlib(install version:3.2.1 version range:*)
| | +- cycler(install version:0.10.0 version range:>=0.10)
| | | +- six(install version:1.14.0 version range:*)
| | +- kiwisolver(install version:1.2.0 version range:>=1.0.1)
| | +- numpy(install version:1.19.0rc1 version range:>=1.11)
| | +- pyparsing(install version:3.0.0a1 version range:>=2.0.1)
| | +- python-dateutil(install version:2.8.1 version range:>=2.1)
| +- numpy(install version:1.19.0rc1 version range:>=1.12,<2.0)
| +- packaging(install version:20.3 version range:*)
| +- pandas(install version:1.0.3 version range:*)
| +- Pillow(install version:7.1.1 version range:*)
| +- pydicom(install version:1.4.2 version range:*)
| +- pynetdicom(install version:1.4.1 version range:*)
| | +- pydicom(install version:1.4.2 version range:>=1.2.1)
| +- python_dateutil(install version: version range:*)
| +- PyYAML(install version:5.3.1 version range:*)
| +- requests(install version:2.23.0 version range:*)
| | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | +- idna(install version:2.9 version range:>=2.5,<3)
| | +- urllib3(install version:1.25.9 version range:>=1.21.1,<1.26)
| +- scikit-image(install version:0.16.2 version range:*)
| +- scipy(install version:1.2.3 version range:*)
| +- shapely(install version:1.7.0 version range:>=1.7.0)
| +- tqdm(install version:4.45.0 version range:*)
| +- watchdog(install version:0.10.2 version range:*)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_numpy_** to be **_>=1.11_**.
2.	Remove your direct dependency **_numpy_**, and use the **_numpy_** transitively introduced by **_matplotlib_**.
3.	Change your direct dependency **_matplotlib_** to be **_<=3.2.1_**.
@SimonBiggs  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by SimonBiggs** [comment]
Hi @NeolithEra,

Thanks for raising this issue. Much appreciated :). I wouldn't want numpy's pinning to drop below 1.12. I also don't believe numpy is planning on a 2.0 release any time soon. However, I don't actually need a <2.0 pin, so I wouldn't have an issue with changing the pinning to >=1.12 only.

For option 3, I really don't want to introduce pinning on the feature and patch level of semantic versioning. So, no to 3. Especially within a library package (as opposed to an application package).

For option 2, due to the internal structure of pymedphys, all of these dependencies at the end of the day are optional. I mark them as hard dependencies just to make the installation more batteries included. Down the line I do intend to have a "pymedphys-base" package which could be installed instead. I don't want to transitivly depend on numpy, because some installations can viably use their desired features with pymedphys + numpy only, with no matplotlib.

A pull request that removes numpy's upper bound, but keeps its lower bound would be most welcome. Thanks :).

Cheers,
Simon
