### ISSUE TITLE
Further discuss pynetdicom workflow for ML tool

### ISSUE THREAD

**Issue by matthewdeancooper** [pymedphys/pymedphys#917]
Hi @SimonBiggs. I have had a good read through the pynetdicom docs and worked through the tutorials and some other examples. I feel like the COM in DICOM was hugely understated when it was introduced to my class! It would be good to fit in a quick "pick your brain" session now that I am familiar with the networking protocol.

**Comment by sjswerdloff** [comment]
Have you looked at OnkoDICOM (given the title of the issue)?
Is this the right place to pose your questions?
If the questions are about DICOM itself, I'd be glad to try to do that in an appropriate channel, and help @SimonBiggs focus on pymedphys.

**Comment by SimonBiggs** [comment]
Heya @matthewdeancooper,

More than happy to do another "picking brain session". :). I've gone and dislocated my thumb... makes programming (and typing) slow going... ... to the point of me not wanting to really bother.

Heya @sjswerdloff,

This is quite pymedphys related. Matt's work was to address https://github.com/pymedphys/pymedphys/issues/82. He just completed his masters focused on that and is currently undergoing writing a CLI based DICOM server that will receive CT DICOM files from a PACS and then forward on to the TPS DICOM structure files. This is purposefully designed to be part of an automated pipeline. No GUI needed, by design. So OnkoDICOM would likely not be appropriate...

Cheers,
Simon

**Comment by sjswerdloff** [comment]
Ah... didn't know the background... nor the social graph.
@matthewdeancooper , if you know what your SCP is expecting so that it knows "when the last CT instance has arrived", or if you know the PACS transmits the full series in one association, great.  Otherwise, be aware that some implementations may transmit something less than the entire sereis in one association.  Some do one instance per association (which is painful in several ways).  Hopefully your image volume is contained in one series.  Some older CT scanners did not do that... 
I encourage you to adhere to the IHE-RO Basic RT Objects Interoperability Profile II as a Contourer (actor).  
See https://www.ihe.net/resources/technical_frameworks/#radiationoncology and http://ihe-ro.org/doku.php?id=doc:profiles
That way if a TPS has problems with your RT Structure Set, you have something to point to and say "what gives?".
While I really like pydicom (and pynetdicom), I don't see that much in the way of validation.  You can validate your output (RT Structue Set) for DICOM conformance using DVTK (dvtk.org) if there isn't a validation tool that you are already using (if there is such a thing within pydicom, I'd love to find out about it).  By now the validation tools for adherence to the IHE-RO profile I mentioned (and the RT SS content) should be available to registered users (no fee) via DVTK.

**Comment by matthewdeancooper** [comment]
Hey @sjswerdloff, appreciate the help!

> Otherwise, be aware that some implementations may transmit something less than the entire series in one association.

My understanding was that each series has one association request and each DICOM file in that series has its own C-STORE request, which is further broken down into ~10 packets. I had not considered that a series may be split across two associations, so this was a good point to raise!

> if you know what your SCP is expecting so that it knows "when the last CT instance has arrived"

I believe the SCP running on the PACS will send a drop association response to the SCU (running on the modality) after it receives a drop association request once all images have been moved. My initial sketch is to add a trigger to this event. We may need to implement something more robust if the series is split over multiple associations.

> if there isn't a validation tool that you are already using...

Not yet! Before I look at validation I still need to work out the best way to create a DICOM structure file and populate it with the information from the DICOM imaging files. Hoping that pydicom has a lot of this covered.
