### ISSUE TITLE
Observable config.toml file

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#953]
* [ ] Have the `config.toml` path be setable via both environment variable and CLI parameter. Have CLI parameter override environment variable.
* [ ] Change the `config.toml` logic to use imports which accepts a list of filepaths which will be pulled into the configuration to allow users to split their config file across a range of files, while still keeping common configurations in a core config file, and flip between them depending on production/development/staging environments, for example.
* [ ] Allow watchdog and `RxPy` to observe the config file in a subscribable way.
* [ ] Have the logging configuration subscribe to changes to the config file and have it reset the logging configuration when that observable fires.

**Comment by SimonBiggs** [comment]
Implement as a Toml backed MutableMapping, the same way that FileDict is implemented within the following talk:

https://youtu.be/S_ipdVNSFlo

**Comment by sjswerdloff** [comment]
As an intermediate step, how about an example config.toml file and initial documentation on what is already configurable.
I'd like to incorporate configuration in to pseudonymisation (specification of a salt value for the hash so that a "site" can share the same salt value to ensure consistent pseudonymisation, while reducing the risk of a rainbow table attack, i.e. precomputed hashes of strings that might be common)

**Comment by SimonBiggs** [comment]
Yup, beautiful. Good call. Will do.
